FROM python:3.9

WORKDIR /app

COPY app.py .
COPY routes.py .
COPY models.py .
COPY test.py .

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENTRYPOINT [ "python" , "app.py"]
